version: '3.3'
services:
  api:
    build: .
    restart: unless-stopped
    ports:
      - 5431:5431
  db:
    image: postgres
    restart: unless-stopped
    environment:
     - POSTGRES_PASSWORD=safepass
    ports:
      - 5432:5432
